name: greetingbirthdayforyou
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  drop_cap_text: ^1.1.3
  lottie: ^2.6.0
  cherry_toast: ^1.5.3
  bottom_navy_bar: ^6.0.0
  persistent_bottom_nav_bar: ^5.0.2
  video_player: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
